name: ${project.parent.artifactId}
version: '${project.parent.version}'
main: me.whereareiam.socialismus.spigot.SocialismusSpigot
api-version: '1.19'
author: whereareiam
softdepend: [
  PlaceholderAPI,
  ProtocolLib
]

libraries:
  - com.google.guava:guava:${guava.version}
  - com.google.inject:guice:${guice.version}
  - net.elytrium:serializer:${serializer.version}
