name: @projectName@
main: me.whereareiam.socialismus.platform.spigot.SocialismusSpigot
version: '@projectVersion@'
api-version: '1.16'
author: whereareiam
softdepend: [
  PlaceholderAPI,
  ProtocolLib
]