name: @projectName@
main: me.whereareiam.socialismus.platform.bukkit.BukkitSocialismus
version: '@projectVersion@'
api-version: '1.16'
author: whereareiam
softdepend: [
  PlaceholderAPI,
  packetevents,
  PAPIProxyBridge
]