name: @projectName@
main: me.whereareiam.socialismus.platform.paper.PaperSocialismus
version: '@projectVersion@'
api-version: '1.20'
folia-supported: true
authors:
  - whereareiam

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    packetevents:
      load: BEFORE
      required: false
      join-classpath: true