name: Release build

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          check-latest: true

      - name: Extract project details
        id: project_details
        run: |
          echo "NAME=$(grep 'rootProject.name' settings.gradle.kts | awk -F "=" '{print $2}' | tr -d ' \"\n')" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF##*/}-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build project
        run: ./gradlew build shadowJar

      - name: Create output directory
        run: mkdir output

      - name: Move API
        run: mv socialismus-common-api/build/libs/socialismus-common-api-${{ env.VERSION }}.jar output/${{ env.NAME }}-API-${{ env.VERSION }}.jar

      - name: Move platform jars
        run: |
          mv socialismus-platform/platform-all/build/libs/${{ env.NAME }}-${{ env.VERSION }}-ALL.jar output/${{ env.NAME }}-ALL-${{ env.VERSION }}.jar
          mv socialismus-platform/platform-paper/build/libs/${{ env.NAME }}-${{ env.VERSION }}-PAPER.jar output/${{ env.NAME }}-PAPER-${{ env.VERSION }}.jar
          mv socialismus-platform/platform-bukkit/build/libs/${{ env.NAME }}-${{ env.VERSION }}-BUKKIT.jar output/${{ env.NAME }}-BUKKIT-${{ env.VERSION }}.jar
          mv socialismus-platform/platform-velocity/build/libs/${{ env.NAME }}-${{ env.VERSION }}-VELOCITY.jar output/${{ env.NAME }}-VELOCITY-${{ env.VERSION }}.jar

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            output/${{ env.NAME }}-API-${{ env.VERSION }}.jar
            output/${{ env.NAME }}-ALL-${{ env.VERSION }}.jar
            output/${{ env.NAME }}-PAPER-${{ env.VERSION }}.jar
            output/${{ env.NAME }}-BUKKIT-${{ env.VERSION }}.jar
            output/${{ env.NAME }}-VELOCITY-${{ env.VERSION }}.jar